import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#ff5625",
        "on-primary-fixed-variant": "#872000",
        "surface-container": "#201f20",
        "surface-dim": "#141314",
        "inverse-primary": "#b12d00",
        "primary-fixed": "#ffdbd1",
        outline: "#ad887e",
        "on-tertiary-fixed": "#3b0900",
        "on-primary": "#601400",
        "surface-container-lowest": "#0f0e0f",
        "on-primary-fixed": "#3b0900",
        "tertiary-fixed": "#ffdbd1",
        "surface-variant": "#363435",
        "on-secondary": "#2f3131",
        "surface-bright": "#3a393a",
        surface: "#141314",
        "outline-variant": "#5d4038",
        "on-secondary-fixed-variant": "#454747",
        "inverse-surface": "#e6e1e2",
        "on-secondary-fixed": "#1a1c1c",
        "secondary-fixed": "#e2e2e2",
        "on-tertiary": "#601400",
        "on-error": "#690005",
        "surface-container-high": "#2b292b",
        "primary-container": "#ff5625",
        primary: "#ffb5a0",
        "surface-container-low": "#1c1b1c",
        "surface-container-highest": "#363435",
        "on-surface": "#e6e1e2",
        "on-tertiary-fixed-variant": "#872000",
        "inverse-on-surface": "#313031",
        error: "#ffb4ab",
        "on-background": "#e6e1e2",
        "secondary-container": "#454747",
        background: "#141314",
        "on-surface-variant": "#e7bdb2",
        secondary: "#c6c6c7",
        "secondary-fixed-dim": "#c6c6c7",
        "tertiary-fixed-dim": "#ffb5a0",
        "on-secondary-container": "#b4b5b5",
        "on-primary-container": "#541100",
        tertiary: "#ffb5a0",
        "on-tertiary-container": "#541100",
        "surface-tint": "#ffb5a0",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#ffb5a0",
      },
      fontFamily: {
        headline: ["Space Grotesk"],
        body: ["Inter"],
        label: ["Geist Mono"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
} satisfies Config;
